name: Version Bump

on:
  push:
    branches:
      - main
      
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v5.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: false
        create_annotated_tag: true
        tag_prefix: v
        release_branches: main
        pre_release_branches: '*'
        dry_run: false
        append_to_pre_release_tag: beta
